controller:
  base-path: /api
  api-calculate-fibonacci: /calculate/fibonacci/{seriesLength}
  api-calculate-fibonacci-limit: /calculate/fibonacci/limite/{limit}
  api-get-all-series-fibonacci: /get/series/all/fibonacci
  api-delete-serie-fibonacci: /delete/serie/fibonacci/{idSerie}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher